### ISSUE TITLE
This line gives an error when running examples.

### ISSUE THREAD

**Issue by clementstross** [gloverd2/admr#19]
https://github.com/gloverd2/admr/blob/ca55b78e6f94ac2d69c06dd7d1af90dc6a221473/R/expl_categorical.R#L33

This line gives an error when running examples, I think it is due to results being assigned twice? Maybe remove the assignments?

**Comment by gloverd2** [comment]
I removed the assignments as per Coding Practices (updating now)
It didn't fail for me?
