### ISSUE TITLE
Import from magrittr

### ISSUE THREAD

**Issue by mdpead** [gloverd2/admr#44]
Might need to more explicitly import the pipe operator from magrittr. I'm sure most people using the package will have loaded it, but still probably best practice. Thinking something like `@importFrom magrittr %>%` in the namespace definition, but I'll need to read up on how it works exactly.

**Comment by CRSlade1** [comment]
Does it not get imported when we call tidyverse? All packages that get called should be in admr/inst/setup.R

**Comment by mdpead** [comment]
When I restart R and load just the ADMR package, then run the following:
```
actual <- rnorm(100, mean=100, sd=10)
weight <- rep(1,100)
predicted <- actual + rnorm(100, mean=0, sd=1)
metric_gini(actual, predicted, weight)
```
I get:
```
Error in data %>% dplyr::group_by(predicted) %>% dplyr::summarise_all(sum) %>%  : 
  could not find function "%>%"
```
Pretty sure it's because although magrittr is loaded, it's not attached, so can't be referenced with just %>%. You could put magrittr::`%>%` infront of every pipe, but then would look awful, so I think you can get around it with a tweak to the namespace.

Let me know if I've done something wrong tho and it works for you.
